package ua.goit.entity.enums;

/**
 * Created by guillaume on 9/14/17.
 */
public enum Industry {

    AGRICULTURE, FORESTRY, FISHING, MINING, CONSTRUCTION, MANUFACTURING, TRANSPORTATION,
    COMMUNICATIONS, ELECTRIC_SERVICES, GAS_SERVICES, SANITARY_SERVICES, WHOLESALE_TRADE, RETAIL_TRADE,
    BANKING, INVESTMENTS, INSURANCE, REAL_ESTATE, SERVICES, PUBLIC_ADMINISTRATION

}
